[sms-simulation]
senders = 4  # Number of senders
messages = 1000  # Total messages to send
failure_rate = 0.1  # Fraction of failed messages (between 0 and 1)
mean_send_time = 0.1  # Average send time in seconds
sdev_send_time = 0.025  # Standard deviation of send time in seconds
refresh = 0.5  # Refresh time in seconds of progress UI
